In [38]:
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVR
import numpy as np

In [40]:
dataset = pd.read_csv('auto-mpg.data', delim_whitespace=True, names=['a','b','c','d','e','f','g','h','CarName'])
dataset.head(5)

      a  b      c      d       e     f   g  h                    CarName
0  18.0  8  307.0  130.0  3504.0  12.0  70  1  chevrolet chevelle malibu
1  15.0  8  350.0  165.0  3693.0  11.5  70  1          buick skylark 320
2  18.0  8  318.0  150.0  3436.0  11.0  70  1         plymouth satellite
3  16.0  8  304.0  150.0  3433.0  12.0  70  1              amc rebel sst
4  17.0  8  302.0  140.0  3449.0  10.5  70  1                ford torino

In [11]:
dataset.tail(15)

,a,b,c,d,e,f,g,h,CarName
383,38.0,4,91.0,67.00,1965.0,15.0,82,3,honda civic
384,32.0,4,91.0,67.00,1965.0,15.7,82,3,honda civic (auto)
385,38.0,4,91.0,67.00,1995.0,16.2,82,3,datsun 310 gx
386,25.0,6,181.0,110.0,2945.0,16.4,82,1,buick century limited
387,38.0,6,262.0,85.00,3015.0,17.0,82,1,oldsmobile cutlass ciera (diesel)
388,26.0,4,156.0,92.00,2585.0,14.5,82,1,chrysler lebaron medallion
389,22.0,6,232.0,112.0,2835.0,14.7,82,1,ford granada l
390,32.0,4,144.0,96.00,2665.0,13.9,82,3,toyota celica gt
391,36.0,4,135.0,84.00,2370.0,13.0,82,1,dodge charger 2.2
392,27.0,4,151.0,90.00,2950.0,17.3,82,1,chevrolet camaro
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

In [41]:
x = dataset.iloc[:, [1,7]]
y = dataset.iloc[:, 8]

In [42]:
scaler = MinMaxScaler(feature_range=(0,1))
x = scaler.fit_transform(x)
print(x)

[[1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.2 1. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.2 1. ]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 0.5]
 [0.6 0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.6 0. ]
 [0.2 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.2 0. ]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 0.5]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 0.5]
 [0.2 0. ]
 [0.2 0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.  1. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 1. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.2 0.5]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.6 0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.  1. ]
 [0.2 0. ]
 [0.6 0. ]
 [0.2 0.5]
 [1.  0. ]
 [1.  0. ]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 0.5]
 [1.  0. ]
 [0.2 0.5]
 [0.6 1. ]
 [1.  0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 0.5]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [1.  0. ]
 [1.  0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.6 0. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 0.5]
 [0.2 1. ]
 [0.6 0. ]
 [0.2 0.5]
 [0.6 0. ]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 1. ]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0.5]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0.5]
 [0.2 1. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.2 0.5]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 0.5]
 [1.  0. ]
 [0.2 0.5]
 [0.6 1. ]
 [0.6 0.5]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 0.5]
 [0.2 0. ]
 [0.2 1. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.2 0.5]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 0.5]
 [0.6 1. ]
 [0.2 0.5]
 [0.  1. ]
 [0.2 0.5]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 1. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.2 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [1.  0. ]
 [0.6 0. ]
 [1.  0. ]
 [1.  0. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.4 0.5]
 [0.6 0.5]
 [0.2 0.5]
 [0.6 0.5]
 [0.2 0.5]
 [0.2 1. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.2 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [1.  0. ]
 [0.2 0.5]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.4 0.5]
 [1.  0. ]
 [0.2 0.5]
 [1.  0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 0.5]
 [0.2 0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.2 0. ]
 [0.2 0.5]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.6 0. ]
 [0.2 0.5]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 0.5]
 [0.2 0.5]
 [0.4 0.5]
 [0.2 0.5]
 [0.2 1. ]
 [0.2 0.5]
 [0.2 1. ]
 [0.2 0.5]
 [0.6 1. ]
 [0.  1. ]
 [0.2 0.5]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.6 0. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0.5]
 [0.2 0.5]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 0.5]
 [0.6 0.5]
 [0.6 1. ]
 [0.6 1. ]
 [0.6 0. ]
 [1.  0. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0.5]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.2 1. ]
 [0.6 0. ]
 [0.6 0. ]
 [0.2 0. ]
 [0.6 0. ]
 [0.2 1. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0.5]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]]

In [43]:
scores= []
best_svr = SVR(kernel='rbf')
cv = KFold(n_splits=7, random_state=7, shuffle= True)
for train_index, test_index in cv.split(x):
    print('Train Index: ', train_index, "\n")
    print('Test Index: ', test_index)
    
    x_train, x_test, y_train, y_test = x[train_index], x[test_index], y[train_index], y[test_index]
    best_svr.fit(x_train,y_train)
    scores.append(best_SVR.score(x_test,y_test))
    print(scores)

Train Index:  [  0   1   2   4   5   6   7   8   9  10  11  12  13  15  16  17  18  19
  20  21  23  24  25  27  29  31  32  33  34  35  36  37  38  39  40  42
  43  44  45  46  47  48  49  50  53  54  55  58  59  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  80  82  83  84  85
  86  87  88  90  91  92  93  94  95  96  97  98  99 100 102 103 104 105
 106 107 108 110 111 112 113 116 117 119 121 122 123 124 125 126 127 128
 130 131 133 134 135 136 137 138 139 141 142 143 144 145 146 147 149 151
 152 153 154 156 157 158 159 160 161 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 182 183 184 185 186 187 189 190 191
 192 193 194 195 196 197 198 199 201 202 203 204 205 208 209 210 211 213
 214 215 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232
 233 234 235 236 237 238 239 240 241 242 243 245 246 247 249 250 251 252
 253 254 255 257 258 259 260 261 262 263 265 266 267 268 270 272 274 275
 276 277 278 279 281 282 283 284 285 286 287 288 289 290 291 292 293 294
 295 296 297 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312
 313 314 315 316 317 318 319 320 321 322 323 325 326 327 329 330 331 333
 335 336 337 338 339 340 341 343 344 345 346 347 348 349 351 352 353 354
 355 356 357 358 359 360 361 362 364 365 366 367 368 369 370 372 373 375
 376 378 379 380 381 382 383 384 385 388 390 391 392 393 394 396 397]

Test Index:  [  3  14  22  26  28  30  41  51  52  56  57  60  79  81  89 101 109 114
 115 118 120 129 132 140 148 150 155 162 181 188 200 206 207 212 216 244
 248 256 264 269 271 273 280 324 328 332 334 342 350 363 371 374 377 386
 387 389 395]

ValueError: could not convert string to float: 'chevrolet chevelle malibu'

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

iris_data = pd.read_csv('iris.data', names=['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm','Species'])

print(iris_data.info())
print('\n')

iris_data['Species'] = iris_data['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2})
iris_data_column_list = list(iris_data.columns)
print(iris_data_column_list)
print('\n')

input_column_list = list(set(iris_data_column_list)-set(['Species']))
print(input_column_list)
print('\n')

output_list = list(['Species'])
print(output_list)
print('\n')

input_column_list.sort()
print(input_column_list)
print('\n')

scaler = StandardScaler()
iris_data[input_column_list] = scaler.fit_transform(iris_data[input_column_list])
print(iris_data)

input_data = iris_data[input_column_list]
covariance_matrix = input_data.cov()
print(covariance_matrix)

eig_vals, eig_vecs = np.linalg.eig(covariance_matrix.to_numpy())
print(eig_vals)
print(eig_vecs)
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range (len(eig_vals))]

#eig_pairs.sort(key = lambda x: x[0], reverse = True)

print('Eigen values in decending orders')
for i in eig_pairs:
    print(i[0],end='\n')
print('\n')
    
threshold =0.95
total_variance = 0.0
count = 0
eigv_sum = np.sum(eig_vals)
for i,j in enumerate(eig_pairs):
    variance_explained = (j[0]/eigv_sum).real
    print('eigenvalue {}: {}'.format(i+1, (j[0]/eigv_sum).real*100))
    total_variance = total_variance + variance_explained
    count = count +1
    
    if (total_variance>=threshold):
        break
print('Total_Variance',total_variance)

len(eig_vecs)
count

reduced_dimension = np.zeros((len(eig_vecs),count))
for i in range(count):
    reduced_dimension[:,i] = eig_pairs[i][1]
    
projected_data = iris_data[input_column_list].to_numpy().dot(reduced_dimension)
projected_dataframe = pd.DataFrame(projected_data, columns=['Feature_1','Feature_2'])

projected_dataframe_with_class_info = pd.concat([projected_dataframe,
                                                 iris_data['Species']],axis=1)

grouped_data = projected_dataframe_with_class_info.groupby(by='Species')

for key in grouped_data.groups.key():
    class_data = grouped_data.get_group(key)
    x = class_data['Feature_1']
    y = class_data['Feature_2']
    plt.scatter(x,y)
    plt.xlabel('Feature_1')
    plt.ylabel('Feature_2')
plt.show()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm', 'Species']


['PetalLengthCm', 'SepalWidthCm', 'PetalWidthCm', 'SepalLengthCm']


['Species']


['PetalLengthCm', 'PetalWidthCm', 'SepalLengthCm', 'SepalWidthCm']


     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0        -0.900681      1.032057      -1.341272     -1.312977        0
1        -1.143017     -0.124958      -1.341272     -1.312977        0
2        -1.385353      0.337848      -1.398138     -1.312977        0
3        -1.506521      0.106445      -1.284407     -1.312977        0
4        -1.021849      1.263460      -1.341272     -1.312977        0
..             ...           ...            ...           ...      ...
145       1.038005     -0.124958       0.819624      1.447956        2
146       0.553333     -1.281972       0.705893      0.922064        2
147       0.795669     -0.124958       0.819624      1.053537        2
148       0.432165      0.800654       0.933356      1.447956        2
149       0.068662     -0.124958       0.762759      0.790591        2

[150 rows x 5 columns]
               PetalLengthCm  PetalWidthCm  SepalLengthCm  SepalWidthCm
PetalLengthCm       1.006711      0.969219       0.877605     -0.423338
PetalWidthCm        0.969219      1.006711       0.823443     -0.358937
SepalLengthCm       0.877605      0.823443       1.006711     -0.110103
SepalWidthCm       -0.423338     -0.358937      -0.110103      1.006711
[2.93035378 0.02074601 0.14834223 0.92740362]
[[ 0.58125401  0.80115427  0.14089226  0.02109478]
 [ 0.56561105 -0.52354627  0.6338014   0.06541577]
 [ 0.52237162 -0.26199559 -0.72101681  0.37231836]
 [-0.26335492  0.12413481  0.24203288  0.92555649]]
Eigen values in decending orders
2.9303537755893134
0.02074601399559576
0.14834222648163983
0.9274036215173411


eigenvalue 1: 72.77045209380134
eigenvalue 2: 0.5151926808906284
eigenvalue 3: 3.6838319576273917
eigenvalue 4: 23.030523267680657
Total_Variance 1.0000000000000002

ValueError: Shape of passed values is (150, 4), indices imply (150, 2)

ValueError: Shape of passed values is (150, 4), indices imply (150, 2)